# Estimation Modes
ESTIMATION_MODE_DIRECT = "DI"
ESTIMATION_MODE_PROGRESS = "PR"
ESTIMATION_MODE_TIME_DONE = "TL"

# Slicers
SLICER_PRUSA = "1"
SLICER_CURA = "2"
SLICER_SIMPLIFY3D = "3"
SLICER_SUPERSLICER = "4"